---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urls
  labels:
    app.kubernetes.io/name: urls
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: urls
  template:
    metadata:
      labels:
        app.kubernetes.io/name: urls
    spec:
      containers:
        - name: urls
          image: urls
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
